import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script
        id="chatway"
        async={true}
        src={`https://cdn.chatway.app/widget.js?id=${process.env.NEXT_PUBLIC_CHATWAY_ID}`}
      ></script>
      <body>{children}</body>
    </html>
  );
}
